version: '3'
 
services:
    server:
        container_name: srver.go.iris
        restart: always
        build: .
        ports:
            - "80:8080" 
        environment:
            PORT: 8080
